development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: myflix
  password: myflixdb

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: myflix
  password: myflixdb